// Получение списка всех постов
GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Получение поста с id = 1
GET /posts?id=1 HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Получение всех комментариев поста с id=2
GET /posts?userId=2&comments HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Обращение к несуществующему пути
GET /posts/gogs?userId=234 HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Удаление альбом по его id
DELETE /albums/1 HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Обновление альбом по его id
PUT /albums/1 HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Создание нового поста
POST /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
###
// Чтение списка альбомов
GET /albums HTTP/1.1
Host: jsonplaceholder.typicode.com